[package]
name = "llama2_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.7"
rayon = "1.5"
matrixmultiply = "0.3"

[profile.release]
debug = true

[features]
model_size = []